name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Insert welcoming text
        run: echo "Hello! and congrats, you have succesfully built and run your firsst GitHub action workflow file "
      - run: echo "$(cat hello_world.txt)"
      
